ARG boost_version=latest
FROM build_env_boost:${boost_version}

MAINTAINER Vannarho
LABEL Description="Build QuantLib and add to the Boost build environment"

# Argument for number of cores to use while building
ARG num_cores

# Exclusions are performed by .dockerignore
COPY QuantLib /ore/QuantLib

RUN cd /ore/QuantLib \
  && mkdir -p build.ql && cd build.ql \
  && cmake .. \
  && make -j ${num_cores} \
  && make install \
  && cd / \
  && rm -rf ore \
  && ldconfig

CMD bash
